# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d1a0af836b6ec7359fb3f2261c6224403973a6a3af5adf5cd944a62e40829b9b5065c3bcca6cf18522e81ea33063f7e53a5a1def9c422403d5ffb3a5ed8d6ab4

test:
  secret_key_base: 9ab8f927668c9b19e7042814ab9145a86f8c0bf42f75ff46ee624c1f7d1d1d44c75a0e82bb5999f15878aa1b927ddec71080782bd77cca65fdf0bf57caf12637

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
